name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Runs every hour
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_stars: yes
          plugin_followup: yes
